# Generated by Django 4.2.2 on 2023-09-21 12:18

import collections
from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('03749053-ebf7-4508-a24b-56e798518fa5'), editable=False, primary_key=True, serialize=False)),
                ('data', jsonfield.fields.JSONField(blank=True, load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True)),
            ],
        ),
    ]
