# Generated by Django 4.2.2 on 2023-09-21 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('600fb7c8-4b39-4c3f-9824-a07879614f03'), editable=False, primary_key=True, serialize=False),
        ),
    ]
